CREATE TABLE Bank(
    BankID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Name VARCHAR(64) NOT NULL,
    Mail VARCHAR(64),
    Telephone VARCHAR(16) NOT NULL,
    LegalAddress VARCHAR(256) NOT NULL
);

CREATE TABLE LoanSubject(
    LoanID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SubjectName VARCHAR(256),
    Debt INTEGER NOT NULL,
    PurchaseDate VARCHAR(10) NOT NULL,
    Price INTEGER NOT NULL
);

CREATE TABLE Hangman(
    HangmanID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Position VARCHAR(8) NOT NULL,
    FirstName VARCHAR(64),
    LastName VARCHAR(64),
    TelephoneNumber VARCHAR(16) NOT NULL,
    FOREIGN KEY (Chief) REFERENCES Hangman(HangmanID)
);

CREATE TABLE Relative(
    RelativeID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FirstName VARCHAR(64),
    LastName VARCHAR(64),
    TelephoneNum VARCHAR(64) NOT NULL,
    HomeAddress VARCHAR(256) NOT NULL,
    FOREIGN KEY (DebtorID) REFERENCES Deptor (DeptorID)
);

CREATE TABLE Deptor(
    DeptorID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FirstName VARCHAR(64) NOT NULL,
    LastName VARCHAR(64) NOT NULL,
    TelephoneNum VARCHAR(16),
    HomeAddress VARCHAR(256),
    FOREIGN KEY (LoanID) REFERENCES LoanSubject(LoanID),
    FOREIGN KEY (BankID) REFERENCES Bank(BankID),
    FOREIGN KEY (HangmanID) REFERENCES Hangman(HangmanID)
);
